package com.unigrative.plugins.panels;

import com.unigrative.plugins.ScannerPlugin;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.awt.*;

public class clientSettingsPanelImpl extends JPanel {

    private static final Logger LOGGER;
    private JComboBox cboSelectedModule;
    private JLabel lblSelectedModule;
    private JPanel pnlMain;
    private JCheckBox chkDebugMode;


    public String getCboSelectedValue() {
        if (cboSelectedModule != null) {
            if (cboSelectedModule.getSelectedItem() != null) {
                return cboSelectedModule.getSelectedItem().toString();

            }
            return null;
        }
        return null;
    }

    public void setCboSelectedValue(String value) {
        if (cboSelectedModule != null) {
            cboSelectedModule.setSelectedItem(value);
        }
    }

    public Boolean getDebugModeValue(){
        return this.chkDebugMode.isSelected();
    }
    public void setChkDebugModeValue(Boolean value){
        this.chkDebugMode.setSelected(value);
    }

    public clientSettingsPanelImpl() {

        initComponents();

    }

    private void initComponents() {



        ///autoGenerated Panel
        pnlMain = new JPanel();
        pnlMain.setLayout(new GridBagLayout());
        cboSelectedModule = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Sales Order");
        defaultComboBoxModel1.addElement("Shipping");
        cboSelectedModule.setModel(defaultComboBoxModel1);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 0.75;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlMain.add(cboSelectedModule, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlMain.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlMain.add(spacer2, gbc);
        lblSelectedModule = new JLabel();
        lblSelectedModule.setText("Pair Scanner with which Module");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 15;
        pnlMain.add(lblSelectedModule, gbc);
        chkDebugMode = new JCheckBox();
        chkDebugMode.setText("Debug Enabled");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        pnlMain.add(chkDebugMode, gbc);

        this.add(pnlMain);

    }
    static {
        LOGGER = LoggerFactory.getLogger(ScannerPlugin.class);
    }
}
