package com.unigrative.plugins.panels;

import javax.swing.*;
import java.awt.*;

public class clientSettingsPanel {
    private JComboBox cboSelectedModule;
    private JLabel lblSelectedModule;
    private JPanel pnlMain;


    public String getCboSelectedValue() {
        if (cboSelectedModule != null) {
            if (cboSelectedModule.getSelectedItem() != null) {
                return cboSelectedModule.getSelectedItem().toString();

            }
            return null;
        }
        return null;
    }

    public void setCboSelectedValue(String value) {
        if (cboSelectedModule != null) {
            cboSelectedModule.setSelectedItem(value);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlMain = new JPanel();
        pnlMain.setLayout(new GridBagLayout());
        cboSelectedModule = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Sales Order");
        defaultComboBoxModel1.addElement("Shipping");
        cboSelectedModule.setModel(defaultComboBoxModel1);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.75;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlMain.add(cboSelectedModule, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlMain.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlMain.add(spacer2, gbc);
        lblSelectedModule = new JLabel();
        lblSelectedModule.setText("Pair Scanner with which Module");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 15;
        pnlMain.add(lblSelectedModule, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlMain;
    }
}
